### ISSUE TITLE
Krang for all methods

### ISSUE THREAD

**Issue by grrigore** [milis92/Krang#26]
Is there a way to use Krang as a default for all methods?

**Comment by milis92** [comment]
Not supported out of the box. Il build something for the following release

**Comment by milis92** [comment]
This is now supported in the latest [snapshot](https://github.com/milis92/Krang/releases/tag/snapshot).
You can now annotate a class, and Krang will intercept all function calls for that particular class.

One extra addition that I took the chance to do is godMode.
God mode will allow you to intercept every function in the codebase, without explicitly annotating a class or a function.
Enabling god mode:
```kotlin
krang {
    enabled.set(true)
    godMode.set(true) // false by default
}
```
@grrigore Please test the latest snapshot and report any findings ;)
